set -g status on
set -g status-position bottom
set -g status-justify left
set -g status-style "bg={{hyprism.background}},fg={{hyprism.onSurface}}"

set -g status-left-length 40
set -g status-left "#[bg={{hyprism.primary}},fg={{hyprism.onPrimary}},bold] 󰣇 #S #[bg={{hyprism.background}},fg={{hyprism.primary}},nobold]"

set -g status-right-length 90
set -g status-right "#[bg={{hyprism.background}},fg={{hyprism.onSurfaceVariant}}] 󰃭 %a %d %b #[fg={{hyprism.outline}}]#[fg={{hyprism.secondary}}] 󰍹 #H #[fg={{hyprism.outline}}]#[fg={{hyprism.primary}}]#[bg={{hyprism.primary}},fg={{hyprism.onPrimary}},bold] 󰥔 %H:%M "

set -g window-status-format "#[bg={{hyprism.background}},fg={{hyprism.onSurfaceVariant}}] 󰖯 #I  #W "
set -g window-status-separator ""
set -g window-status-current-format "#[bg={{hyprism.surfaceActive}},fg={{hyprism.background}}]#[bg={{hyprism.surfaceActive}},fg={{hyprism.onSurface}},bold] 󰖯 #I  #W #[bg={{hyprism.background}},fg={{hyprism.surfaceActive}}]"
set -g window-status-bell-style "bg={{hyprism.error}},fg={{hyprism.onError}},bold"

set -g pane-border-style "fg={{hyprism.outline}}"
set -g pane-active-border-style "fg={{hyprism.primary}}"
set -g pane-border-lines single
set -g display-panes-colour "{{hyprism.outline}}"
set -g display-panes-active-colour "{{hyprism.primary}}"

set -g message-style "bg={{hyprism.surface}},fg={{hyprism.onSurface}},bold"
set -g message-command-style "bg={{hyprism.surfaceContainerHigh}},fg={{hyprism.secondary}}"
set -g clock-mode-colour "{{hyprism.primary}}"
set -g clock-mode-style 24
set -g mode-style "bg={{hyprism.onSurface}},fg={{hyprism.background}}"
