[General]
background=file:///var/lib/hyprism/sddm/current-wallpaper.jpg
background-color=#091015
surface-color=#131b21
surface-hover-color=#202b33
foreground-color=#e0e8ee
muted-color=#9aa8b2
accent-color=#82b1d3
accent-foreground-color=#091015
error-color=#e4777f
