font_family = Google Sans Flex
font_family_monospace = JetBrainsMono Nerd Font
h1_size = 28
h2_size = 18
h3_size = 14
font_size = 12
small_font_size = 10
icon_theme = Hyprism-Papirus
rounding_large = 16
rounding_small = 9
source = ~/.cache/hyprism/theme/hyprtoolkit-colors.conf
