$hyprism_background = rgb(091015)
$hyprism_surface = rgb(18232a)
$hyprism_surface_active = rgb(203640)
$hyprism_foreground = rgb(e0e8ee)
$hyprism_muted = rgb(87949e)
$hyprism_accent = rgb(3ba7d9)
$hyprism_error = rgb(e4777f)

source = ~/.cache/hyprism/theme/hyprlock-colors.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.cache/hyprism/state/lock-wallpaper
    color = $hyprism_background
    blur_passes = 3
    blur_size = 8
    brightness = 0.72
}

label {
    monitor =
    text = $TIME
    color = $hyprism_foreground
    font_family = Google Sans Flex
    font_size = 74
    position = 0, 128
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +'%d/%m/%Y'
    color = $hyprism_muted
    font_family = Google Sans Flex
    font_size = 16
    position = 0, 66
    halign = center
    valign = center
}

label {
    monitor =
    text = 󰌾
    color = $hyprism_accent
    font_family = Symbols Nerd Font Mono
    font_size = 14
    position = -60, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = Bloqueado
    color = $hyprism_accent
    font_family = Google Sans Flex
    font_size = 14
    position = 14, -50
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 360, 54
    position = 0, -112
    halign = center
    valign = center
    outline_thickness = 2
    rounding = 9
    outer_color = $hyprism_accent
    inner_color = $hyprism_surface
    font_color = $hyprism_foreground
    check_color = $hyprism_accent
    fail_color = $hyprism_error
    capslock_color = $hyprism_error
    font_family = Google Sans Flex
    placeholder_text = Digite sua senha
    fail_text = Senha incorreta
    dots_center = true
    fade_on_empty = false
}
