allow_remote_control yes
listen_on unix:${XDG_RUNTIME_DIR}/kitty

foreground #e0e8ee
background #091015
cursor #82b1d3
selection_foreground #e0e8ee
selection_background #202b33
active_border_color #82b1d3
inactive_border_color #426172
include ~/.cache/hyprism/theme/kitty.conf

font_family JetBrainsMono Nerd Font
font_size 11.5
window_padding_width 10
confirm_os_window_close 0
enable_audio_bell no
background_opacity 0.88
