set -g prefix C-b
unbind C-a
bind C-b send-prefix

set -g mouse on

set -g history-limit 10000

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

set -g escape-time 10
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

bind c new-window -c "#{pane_current_path}"
bind n next-window
bind p previous-window
bind Tab last-window
bind & kill-window

bind X confirm-before -p "Close the current session (#S) and all windows? (y/n)" kill-session
bind Q confirm-before -p "Close ALL tmux sessions? (y/n)" kill-server

bind x kill-pane
bind z resize-pane -Z
bind q display-panes

bind [ copy-mode
bind ] paste-buffer

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

set -g status-position bottom
set -g status-interval 1

source-file -q ~/.config/tmux/theme.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

run '~/.tmux/plugins/tpm/tpm'
